version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: erp-api
    restart: unless-stopped
    ports:
      - "1303:1303"
    environment:
      - NODE_ENV=production
      - PORT=1303
      # Diğer ortam değişkenleri Azure App Service'te veya Azure Key Vault'ta tanımlanacak
    volumes:
      - ./logs:/app/logs
