name: erp-backend

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: erp-backend
    ports:
      - "1303:1303"
    environment:
      - NODE_ENV=production
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=xderensa3
      - DB_NAME=erp_db
      - DATABASE_URL=postgresql://postgres:xderensa3@postgres:5432/erp_db?schema=public
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

    develop:
      watch:
        - action: sync
          path: .
          target: /app
          ignore:
            - node_modules/
            - .git/
            - .gitignore
        - action: rebuild
          path: package.json

  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: erp_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: xderensa3
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
