name: erp-backend

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: erp-backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=915307dedd66bANEA
      - DB_NAME=erp_db
      - DATABASE_URL="postgresql://postgres:xderensa3@localhost:5432/erp_db?schema=public"
    depends_on:
      - postgres
    develop:
      watch:
        - action: sync
          path: .
          target: /app
          ignore:
            - node_modules/
            - .git/
            - .gitignore
        - action: rebuild
          path: package.json

  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: erp_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: xderensa3
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
